env_parameters:
  env_name: "StackCustom"
  robots: ["Indy7"]
  controller: "config/controller/indy7_absolute_pose.json"
  prehensile: False
  camera_names: ["robot0_eye_in_hand_back", "agentview", "robot0_eye_in_hand"] # To be contained in the raw dataset
  camera_heights: 256
  camera_widths: 256
  camera_depths: False
  control_freq: 20
  seed: 0
  max_iter: 1000
  fix_initial_cube_pose: False


task_parameters:
  num_episodes : 50
  episode_len: 250
  raw_dataset_dir: "data_collection/datasets/stack"
  processed_dataset_dir: "data_collection/datasets/stack/s_world_pose_a_world_pose"
  ckpt_dir: "act/ckpt/stack/s_world_pose_a_world_pose"
  camera_names: ["robot0_eye_in_hand", "robot0_eye_in_hand_back"] # To be contained in the processed dataset
  stage: 0
  state_category: ["world_pose"]
  action_category: ["world_pose", "gripper"]
  state_dim : 9
  action_dim : 10
  noisy_reference : False
  noisy_reference_type : "random" # "fixed" or "random"
  num_queries: 40
  
eval_parameters:
  num_episodes : 50
  episode_len: 350
  ckpt_dir: "act/ckpt/stack/s_world_pose_a_world_pose"
  camera_names: ["robot0_eye_in_hand", "robot0_eye_in_hand_back"] # To be contained in the processed dataset
  stage: 0
  state_category: ["world_pose"]
  action_category: ["world_pose", "gripper"]
  state_dim : 9
  action_dim : 10
  noisy_reference : True
  noisy_reference_type : "fixed"